server:
  port: 8000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: user
    password: secret
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Or create, create-drop, none
    show-sql: true # Optional: to log SQL statements

#resilience4j configuration
resilience4j.retry:
  instances:
    feignClient:
      maxAttempts: 4
      waitDuration: 1s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      #retryExceptions:
        #- feign.RetryableException